# spring.application.name=jt-blog

# server.port = 1205

# spring.datasource.url=jdbc:mysql://localhost/blog
# spring.datasource.username=root
# spring.datasource.password=Rakesh

spring:
    application:
        name: jt-blogs

    sql:
        init:
            mode: never

    datasource:
        url: jdbc:mysql://localhost/blog?createDatabaseIfNotExist=true
        username: root
        password: Rakesh

server:
    port: 1205        