# spring.application.name=jt-blog

# server.port = 1205

# spring.datasource.url=jdbc:mysql://localhost/blog
# spring.datasource.username=root
# spring.datasource.password=Rakesh

spring:
    application:
        name: jt-blogs
    datasource:
        url: jdbc:mysql://localhost/blog
        username: root
        password: Rakesh

server:
    port: 1205        